session_name: tartan_rgbt_drivers
options:
  mouse: on
windows:
  - window_name: Camera Drivers
    suppress_history: false
    layout: tiled
    panes:
      - shell_command:
        - sleep 60 
        - echo "Initializing ZED Driver."
        - echo "Sourcing ROS 2 and workspace setup."
        - source /root/tartan_rgbt_ws/install/setup.bash
        - ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedx
      - shell_command:
        - sleep 75
        - echo "Initializing Thermal Camera Drivers."
        - echo "Sourcing ROS 2 and workspace setup."
        - source /root/tartan_rgbt_ws/install/setup.bash
        - ros2 launch flir_ros_sync with_prerocess_both_cam.launch.py
  - window_name: Health Drivers
    suppress_history: false
    layout: tiled
    panes:
      - shell_command:
        - echo "Initializing HEalth Driver."
        - echo "Sourcing ROS 2 and workspace setup."
        - source /root/tartan_rgbt_ws/install/setup.bash
        - ros2 launch health_test parv_payload.launch.py
  - window_name: Bag Recorder
    suppress_history: false
    layout: tiled
    panes:
      - shell_command:
        - sleep 80
        - echo "Starting Bag Recorder."
        - echo "Sourcing ROS 2 and workspace setup."
        - source /root/tartan_rgbt_ws/install/setup.bash
        - ros2 launch bag_record_pid bag_record_pid.launch.py